package level1.cache;

import org.hibernate.Session;

import pojo.classes.City;
import utility.classses.GetSessionFactroyObjects;

public class Controller {
	
	public static void main(String[] args) {
		// example 1 >> here 2 select query generated by hibernate 1 for 101 & 1 for 102
//		Session s1 = GetSessionFactroyObjects.getSessionFactory().openSession();
//		City c1 = s1.get(City.class, 101);
//		System.out.println(c1);
//		System.out.println("---------------------------------------");
//		City c2 = s1.get(City.class, 101);
//		System.out.println(c2);
//		System.out.println("---------------------------------------");
//		City c3 = s1.get(City.class, 101);
//		System.out.println(c3);
//		System.out.println("---------------------------------------");
//		City c4 = s1.get(City.class, 102);
//		System.out.println(c4);
//    	s1.close();
		
		// example 2
		
//		Session s2 = GetSessionFactroyObjects.getSessionFactory().openSession();
//		City c6 = s2.get(City.class, 101);
//		System.out.println(c6);
//		
//		System.out.println("---------------------------------------");
//		
//		Session s3 = GetSessionFactroyObjects.getSessionFactory().openSession();
//		City c7 = s3.get(City.class, 101);
//		System.out.println(c7);
		
		// example 3 cache with load method
		
//		Session s2 = GetSessionFactroyObjects.getSessionFactory().openSession();
//		City c6 = s2.load(City.class, 101);
//		System.out.println(c6);
//		
//		System.out.println("---------------------------------------");
//		
//		Session s3 = GetSessionFactroyObjects.getSessionFactory().openSession();
//		City c7 = s3.load(City.class, 101);
//		System.out.println(c7);
		
		
	}

}
